kind: ConfigMap
apiVersion: v1
metadata:
  name: container-azm-ms-agentconfig
  namespace: kube-system
data:
  log-data-collection-settings: |-
    [log_collection_settings.stdout]
      enabled = true
      containerlog_schema_version = "v2"
    [log_collection_settings.stderr]
      enabled = true
      containerlog_schema_version = "v2"