apiVersion: v1
kind: Service
metadata:
  name: spring-api-service  # This is the name you'll see in Freelens
spec:
  type: LoadBalancer        # This tells Azure to give you a Public IP
  ports:
    - port: 80              # The port you'll use in the browser/Postman
      targetPort: 8080      # The port inside your Docker container
  selector:
    app: spring-api